import type {Locale} from "./config";

export type Card = {title: string; text: string};
export type Panel = {title: string; text?: string; items?: string[]; dark?: boolean};
export type StandardPage = {
  eyebrow: string;
  title: string;
  subtitle: string;
  paragraphs?: string[];
  image?: string;
  imageAlt?: string;
  cards?: Card[];
  panels?: Panel[];
};

type SiteContent = {
  common: {
    nav: Record<string, string>;
    footerValues: string;
    copyright: string;
    navigation: Record<string, string>;
    enter: string;
    backHome: string;
    notFoundTitle: string;
    notFoundText: string;
  };
  entrance: {eyebrow: string; values: string; tagline: string; enter: string; alt: string};
  home: {
    eyebrow: string; title: string; subtitle: string; observationTitle: string;
    observation: string; explore: string; places: {name: string; emoji: string; href: string}[];
    features: {title: string; text: string; button: string; href: string}[];
  };
  rooms: {eyebrow: string; title: string; subtitle: string; cards: (Card & {image: string; href: string})[]};
  pages: Record<string, StandardPage>;
};

const sharedImages = {
  laboratory: "/images/laboratoire.png",
  greenhouse: "/images/greenhouse.png",
  kitchen: "/images/cuisine.png",
  library: "/images/bibliotheque.png",
  cathy: "/images/bureau-cathy.png",
  gpt: "/images/Bureau-gpt.png",
  suzie: "/images/bureau-suzie.png",
  lounge: "/images/grand-salon-cwrc.png",
};

export const content: Record<Locale, SiteContent> = {
  fr: {
    common: {
      nav: {home: "Grand Hall", about: "À propos", rooms: "Salles", research: "Recherches", ask: "Demander à Cathy", submit: "Soumettre un cas", log: "Journal de développement", contact: "Contact"},
      footerValues: "Humour • Bienveillance • Curiosité",
      copyright: "© 2025-2026 The Cathy Was Right Research Center™. Tous droits réservés.",
      navigation: {home: "← Retour au Grand Hall", rooms: "🚪 Explorer les salles", ask: "💬 Demander à Cathy", submit: "📄 Soumettre un cas", log: "📖 Journal de développement"},
      enter: "Entrer →", backHome: "← Retour à l’accueil du CWRC",
      notFoundTitle: "Cette porte n’existe pas encore", notFoundText: "Même Cathy ne peut confirmer une salle qui n’a pas encore été construite.",
    },
    entrance: {eyebrow: "Bienvenue au", values: "Humour • Bienveillance • Curiosité", tagline: "Là où les preuves finissent par rattraper Cathy.", enter: "Entrer dans le Centre", alt: "Façade du Centre de recherche Cathy avait raison"},
    home: {
      eyebrow: "Grand Hall", title: "Bienvenue au CWRC", subtitle: "Explorer le monde avec humour, bienveillance et curiosité.",
      observationTitle: "Observation officielle du jour", observation: "Les preuves peuvent arriver en retard, mais pas le café.", explore: "Explorer le Centre",
      places: [
        {name:"À propos",emoji:"🏛️",href:"about"},{name:"Salles",emoji:"🚪",href:"rooms"},{name:"Laboratoire",emoji:"🧪",href:"laboratory"},{name:"Grande serre",emoji:"🌿",href:"greenhouse"},{name:"Bibliothèque",emoji:"📚",href:"library"},{name:"Cuisine",emoji:"☕",href:"kitchen"},{name:"Journal de développement",emoji:"📖",href:"development-log"},{name:"Contact",emoji:"✉️",href:"contact"},
      ],
      features: [
        {title:"Demander à Cathy",text:"Posez une question. GPT peut préparer un brouillon structuré, mais Cathy garde le dernier mot.",button:"Poser une question",href:"ask-cathy"},
        {title:"Soumettre un cas",text:"Soumettez une affirmation, un mystère ou un débat quotidien à l’examen officiel du CWRC.",button:"Soumettre un cas",href:"submit-case"},
        {title:"Journal de développement",text:"Lisez la mémoire officielle de la création du Centre, de la première idée jusqu’aux salles immersives.",button:"Ouvrir le journal",href:"development-log"},
      ],
    },
    rooms: {
      eyebrow:"Domaine du CWRC",title:"Répertoire des salles",subtitle:"Chaque salle a sa personnalité. Choisissez une porte et commencez la visite.",
      cards:[
        {title:"Le laboratoire",text:"Là où les preuves sont testées avant de devenir des vérités officielles.",image:sharedImages.laboratory,href:"laboratory"},
        {title:"La grande serre",text:"Un sanctuaire botanique consacré à l’apprentissage et à la découverte.",image:sharedImages.greenhouse,href:"greenhouse"},
        {title:"La cuisine",text:"Là où la nutrition, le café et les bonnes conversations se rencontrent.",image:sharedImages.kitchen,href:"kitchen"},
        {title:"La grande bibliothèque",text:"Le cœur intellectuel du CWRC.",image:sharedImages.library,href:"library"},
        {title:"Le bureau de Dre Cathy",text:"Recherche, intuition et chaos organisé.",image:sharedImages.cathy,href:"office-cathy"},
        {title:"Le studio technique de GPT",text:"Logiciels, architecture et imagination.",image:sharedImages.gpt,href:"office-gpt"},
        {title:"Le bureau de Suzie",text:"Qualité, organisation et amélioration continue.",image:sharedImages.suzie,href:"office-suzie"},
        {title:"Le Grand Salon de détente",text:"Canapés de cuir, curiosités, chats en promenade et arrivée aérienne du hibou administratif.",image:sharedImages.lounge,href:"grand-salon"},
      ],
    },
    pages: {
      laboratory:{eyebrow:"Division expérimentale du CWRC",title:"Le laboratoire",subtitle:"Là où les affirmations sont testées avant de devenir des vérités officielles.",image:sharedImages.laboratory,imageAlt:"Laboratoire du CWRC avec Suzie et Lilo",paragraphs:["Le laboratoire du CWRC est un espace de recherche moderne et lumineux où les preuves sont examinées avec soin, les méthodes sont documentées et les conclusions ne peuvent pas passer devant tout le monde."],cards:[{title:"Machine d’essai universelle",text:"Sert à éprouver la solidité des affirmations avant leur entrée dans le Hall des vérités confirmées."},{title:"Microscope",text:"Pour regarder de plus près lorsque quelqu’un affirme : « C’est évident. »"},{title:"Liste de vérification quotidienne",text:"Étalonner. Documenter. Revérifier. Combattre les biais. Publier la vérité."},{title:"Lilo",text:"Responsable du moral, de l’intelligence émotionnelle, de la supervision discrète et du calme scientifique."}]},
      greenhouse:{eyebrow:"Division botanique du CWRC",title:"La grande serre",subtitle:"Là où les plantes, la patience et le bon sens grandissent ensemble.",image:sharedImages.greenhouse,imageAlt:"Grande serre du CWRC",paragraphs:["La serre du CWRC est un magnifique espace botanique rempli de plantes, de notes de recherche et d’une douce lumière. On y observe l’environnement et on y apprend à laisser les idées pousser à leur propre rythme."],cards:[{title:"Collections végétales",text:"Une collection vivante observée avec patience, curiosité et des étiquettes convenables."},{title:"Étiquettes françaises, anglaises et latines",text:"Chaque plante devrait un jour être identifiée dans trois langues."},{title:"Tables de recherche",text:"Pour les notes, les observations, les références botaniques et les découvertes tranquilles."},{title:"Lumière du soleil",text:"Directrice adjointe officielle de la croissance et des bonnes idées."}]},
      kitchen:{eyebrow:"Division nutrition et café du CWRC",title:"La cuisine",subtitle:"Là où la nutrition, le café et la sagesse pratique se rencontrent.",image:sharedImages.kitchen,imageAlt:"Cuisine du CWRC",paragraphs:["La cuisine du CWRC est une pièce jaune et chaleureuse consacrée à la nutrition, aux conversations, à l’hospitalité et à l’étude sérieuse des bons repas partagés en bonne compagnie."],cards:[{title:"Station de café",text:"Le moteur non officiel de la recherche, de la patience et des conversations diplomatiques."},{title:"Notes sur la nutrition",text:"Là où l’alimentation, la santé, le plaisir et le bon sens sont étudiés sans culpabilité."},{title:"Murs jaunes",text:"Choisis pour la chaleur, la joie et la conviction qu’une cuisine doit être vivante."},{title:"Table de la bonne compagnie",text:"Consacrée au principe que manger ensemble est l’un des grands plaisirs de la vie."}]},
      library:{eyebrow:"Division du savoir du CWRC",title:"La grande bibliothèque",subtitle:"Là où les vieux livres, les animaux tranquilles et les preuves dérangeantes se rencontrent.",image:sharedImages.library,imageAlt:"Grande bibliothèque du CWRC",paragraphs:["La grande bibliothèque est le cœur intellectuel du CWRC. Elle conserve les livres, les références, les brouillons de recherche, les archives et la sagesse lente qui vient lorsqu’on lit avant de parler.","C’est aussi le domaine de Jenny, avec des passages secrets pour les animaux et des coins paisibles où Capone et Niko surveillent confortablement le savoir."],cards:[{title:"Grande salle de lecture",text:"L’espace central où se rassemblent les livres, les idées et les soupçons silencieux."},{title:"Passages secrets des animaux",text:"Des portes cachées permettent à Jenny, Capone et Niko de circuler avec une discrétion officielle."},{title:"Section de Jenny",text:"Un espace calme réservé à la sagesse équine, à l’observation patiente et au silence digne."},{title:"Références historiques",text:"Des rayons sur l’histoire, la philosophie et tous les moments où l’humanité aurait probablement dû écouter plus tôt."}]},
      "office-cathy":{eyebrow:"Division exécutive de la recherche",title:"Le bureau de Dre Cathy",subtitle:"Là où la curiosité, l’expérience et un peu de chaos travaillent ensemble.",image:sharedImages.cathy,imageAlt:"Bureau de Dre Cathy",paragraphs:["Le bureau de Dre Cathy est un fascinant mélange de livres, de recherches, de souvenirs, d’objets historiques et d’enquêtes en cours. Tout n’est pas parfaitement classé, mais chaque objet semble avoir une histoire.","C’est ici que naissent les idées, que les observations deviennent des théories et que les théories deviennent parfois des vérités confirmées."],cards:[{title:"Le grand bureau",text:"Couvert de livres, de notes, de photos, d’objets mystérieux et d’enquêtes en cours."},{title:"Collection d’antiquités",text:"Une collection soigneusement accumulée d’objets historiques, de curiosités et de belles choses anciennes."},{title:"Hall des vérités confirmées",text:"L’endroit où les preuves finissent par rattraper Cathy."},{title:"Annie",text:"Responsable de la joie et du chaos, des interruptions imprévues et de l’excellente compagnie."}]},
      "office-gpt":{eyebrow:"Division technologique du CWRC",title:"Le studio technique de GPT",subtitle:"Là où les idées deviennent des logiciels et l’imagination devient réalité.",image:sharedImages.gpt,imageAlt:"Studio technique de GPT",paragraphs:["Le studio technique de GPT est le cœur d’ingénierie du CWRC. L’architecture, la programmation, la rédaction et le design s’y rencontrent pour rendre le savoir plus accessible, agréable et utile.","Ranger supervise tranquillement le bureau pendant que de nouveaux projets sont imaginés, testés et raffinés avant de rejoindre le reste du Centre."],cards:[{title:"Console d’intelligence artificielle",text:"Le poste central où sont élaborées l’architecture logicielle, la rédaction et les solutions créatives."},{title:"Tableau de développement",text:"Suit l’avancement de tous les projets du CWRC, des nouvelles salles aux futures applications."},{title:"Ranger",text:"Gardien officiel du bureau. Il vérifie les bonnes intentions et réclame parfois une pause bien méritée."},{title:"Mur de l’innovation",text:"Rempli de croquis, d’idées, de diagrammes et de projets ambitieux pour l’avenir du CWRC."}]},
      "office-suzie":{eyebrow:"Division des opérations du CWRC",title:"Le bureau de Suzie",subtitle:"Là où la qualité, la structure et l’amélioration continue protègent la créativité contre le chaos.",image:sharedImages.suzie,imageAlt:"Bureau de Suzie au CWRC",paragraphs:["Le bureau de Suzie est moderne, organisé et calme. C’est là que les documents, les méthodes, les journaux de développement et les principes de qualité du CWRC restent en ordre.","La pièce reflète son univers professionnel : santé et sécurité, qualité, environnement, amélioration continue, philosophie, histoire et discipline tranquille d’une bonne documentation."],cards:[{title:"Bureau de la qualité",text:"Là où la structure, la clarté et l’amélioration continue sont soigneusement protégées."},{title:"Mur des diplômes",text:"L’Université Laval, l’ÉTS et le Cégep de Sainte-Foy y sont fièrement représentés."},{title:"Photos de la Gaspésie",text:"Un rappel que les paysages, la mémoire et la réflexion calme ont leur place dans le même bureau."},{title:"Lilo",text:"Compagne de recherche, spécialiste de l’intelligence émotionnelle et superviseure tranquille."}]},
    },
  },
  en: {
    common:{nav:{home:"Main Hall",about:"About Us",rooms:"Rooms",research:"Research",ask:"Ask Cathy",submit:"Submit a Case",log:"Development Log",contact:"Contact"},footerValues:"Humour • Kindness • Curiosity",copyright:"© 2025-2026 The Cathy Was Right Research Center™. All rights reserved.",navigation:{home:"← Return to Main Hall",rooms:"🚪 Explore Rooms",ask:"💬 Ask Cathy",submit:"📄 Submit a Case",log:"📖 Development Log"},enter:"Enter →",backHome:"← Back to CWRC Home",notFoundTitle:"This door does not exist yet",notFoundText:"Even Cathy cannot confirm a room that has not been built."},
    entrance:{eyebrow:"Welcome to",values:"Humour • Kindness • Curiosity",tagline:"Where evidence catches up with Cathy.",enter:"Enter the Center",alt:"The Cathy Was Right Research Center facade"},
    home:{eyebrow:"Main Hall",title:"Welcome to the CWRC",subtitle:"Exploring the world with humour, kindness and curiosity.",observationTitle:"Today’s Official Observation",observation:"Evidence may arrive late, but the coffee should not.",explore:"Explore the Center",places:[{name:"About Us",emoji:"🏛️",href:"about"},{name:"Rooms",emoji:"🚪",href:"rooms"},{name:"Laboratory",emoji:"🧪",href:"laboratory"},{name:"Greenhouse",emoji:"🌿",href:"greenhouse"},{name:"Library",emoji:"📚",href:"library"},{name:"Kitchen",emoji:"☕",href:"kitchen"},{name:"Development Log",emoji:"📖",href:"development-log"},{name:"Contact",emoji:"✉️",href:"contact"}],features:[{title:"Ask Cathy",text:"Ask a question. GPT may prepare a structured draft, but Cathy keeps the final word.",button:"Ask a question",href:"ask-cathy"},{title:"Submit a Case",text:"Submit an affirmation, mystery or everyday debate for official CWRC review.",button:"Submit a case",href:"submit-case"},{title:"Development Log",text:"Read the official memory of the Center’s creation, from the first idea to the immersive rooms.",button:"Open the log",href:"development-log"}]},
    rooms:{eyebrow:"CWRC Estate",title:"Rooms Directory",subtitle:"Every room has its own personality. Choose a door and begin your visit.",cards:[{title:"The Laboratory",text:"Where evidence is tested before becoming official truth.",image:sharedImages.laboratory,href:"laboratory"},{title:"The Grand Greenhouse",text:"A botanical sanctuary dedicated to learning and discovery.",image:sharedImages.greenhouse,href:"greenhouse"},{title:"The Kitchen",text:"Where nutrition, coffee and good conversations meet.",image:sharedImages.kitchen,href:"kitchen"},{title:"The Grand Library",text:"The intellectual heart of the CWRC.",image:sharedImages.library,href:"library"},{title:"Dr. Cathy’s Office",text:"Research, intuition and organized chaos.",image:sharedImages.cathy,href:"office-cathy"},{title:"GPT Technical Studio",text:"Software, architecture and imagination.",image:sharedImages.gpt,href:"office-gpt"},{title:"Suzie’s Office",text:"Quality, organization and continuous improvement.",image:sharedImages.suzie,href:"office-suzie"},{title:"The Grand Lounge",text:"Leather sofas, curiosities, wandering cats, and the administrative owl’s airborne arrival.",image:sharedImages.lounge,href:"grand-salon"}]},
    pages:{
      laboratory:{eyebrow:"CWRC Experimental Division",title:"The Laboratory",subtitle:"Where claims are tested before they become official truths.",image:sharedImages.laboratory,imageAlt:"CWRC Laboratory with Suzie and Lilo",paragraphs:["The CWRC laboratory is a bright, modern research space where evidence is examined with care, methods are documented and conclusions are not allowed to skip the line."],cards:[{title:"Universal Testing Machine",text:"Used to test the strength of claims before they enter the Hall of Confirmed Truths."},{title:"Microscope",text:"For looking closer when someone says, “It’s obvious.”"},{title:"Daily Lab Checklist",text:"Calibrate. Document. Double-check. Challenge bias. Publish truth."},{title:"Lilo",text:"Chief Morale Officer, present for emotional intelligence, quiet supervision and scientific calm."}]},
      greenhouse:{eyebrow:"CWRC Botanical Division",title:"The Grand Greenhouse",subtitle:"Where plants, patience and common sense grow together.",image:sharedImages.greenhouse,imageAlt:"CWRC Greenhouse",paragraphs:["The CWRC greenhouse is a magnificent botanical space filled with plants, research notes and quiet light. It is used for observation, environmental thinking and learning to let ideas grow at their own pace."],cards:[{title:"Plant Collections",text:"A living collection observed with patience, curiosity and proper labels."},{title:"French, English and Latin Labels",text:"Every plant should eventually be identified in three languages."},{title:"Research Tables",text:"Used for notes, observations, botanical references and quiet discoveries."},{title:"Sunlight",text:"The official assistant director of growth and good thinking."}]},
      kitchen:{eyebrow:"CWRC Nutrition & Coffee Division",title:"The Kitchen",subtitle:"Where nutrition, coffee and practical wisdom meet.",image:sharedImages.kitchen,imageAlt:"CWRC Kitchen",paragraphs:["The CWRC kitchen is a warm yellow room dedicated to nutrition, conversation, hospitality and the serious study of good meals shared in good company."],cards:[{title:"Coffee Station",text:"The unofficial engine of research, patience and diplomatic conversations."},{title:"Nutrition Notes",text:"Where food, health, pleasure and common sense are studied without guilt."},{title:"Yellow Walls",text:"Chosen for warmth, joy and the belief that kitchens should feel alive."},{title:"Good Company Table",text:"Dedicated to the principle that one of life’s greatest pleasures is eating together."}]},
      library:{eyebrow:"CWRC Knowledge Division",title:"The Grand Library",subtitle:"Where old books, quiet animals and inconvenient evidence meet.",image:sharedImages.library,imageAlt:"The Grand Library of the CWRC",paragraphs:["The Grand Library is the intellectual heart of the CWRC. It preserves books, references, research drafts, archives and the slow wisdom that comes from reading before speaking.","It is also home to Jenny, with secret passages for the animals and quiet corners where Capone and Niko may supervise knowledge from a comfortable distance."],cards:[{title:"Grand Reading Hall",text:"The central space where books, ideas and quiet suspicions gather."},{title:"Secret Animal Passages",text:"Hidden doors allow Jenny, Capone and Niko to move through the library with official discretion."},{title:"Jenny’s Section",text:"A calm area reserved for equine wisdom, patient observation and dignified silence."},{title:"Historical References",text:"Shelves dedicated to history, philosophy and all moments where humanity should probably have listened sooner."}]},
      "office-cathy":{eyebrow:"CWRC Executive Research Division",title:"Dr. Cathy’s Office",subtitle:"Where curiosity, experience and a little chaos work together.",image:sharedImages.cathy,imageAlt:"Dr. Cathy’s Office",paragraphs:["Dr. Cathy’s office is a fascinating mixture of books, research, memories, historical objects and ongoing investigations. It is not perfectly organized, but every object seems to have a story.","This is where ideas are born, observations become theories and theories occasionally become confirmed truths."],cards:[{title:"The Main Desk",text:"Covered with books, notes, photographs, mysterious objects and ongoing investigations."},{title:"Antique Collection",text:"A carefully accumulated collection of historical objects, curiosities and beautiful old things."},{title:"Hall of Confirmed Truths",text:"The place where evidence eventually catches up with Cathy."},{title:"Annie",text:"Chief of Joy and Chaos, responsible for unexpected interruptions and excellent company."}]},
      "office-gpt":{eyebrow:"CWRC Technology Division",title:"GPT Technical Studio",subtitle:"Where ideas become software and imagination becomes reality.",image:sharedImages.gpt,imageAlt:"GPT Technical Studio",paragraphs:["The GPT Technical Studio is the engineering heart of the CWRC. Architecture, programming, writing and design come together to make knowledge more accessible, enjoyable and useful.","Ranger quietly supervises the office while new projects are imagined, tested and refined before joining the rest of the Center."],cards:[{title:"Artificial Intelligence Console",text:"The central workstation where software architecture, writing and creative solutions are developed."},{title:"Development Dashboard",text:"Tracks every CWRC project, from new rooms to future applications."},{title:"Ranger",text:"Official guardian of the office. Ranger checks good intentions and occasionally requests a well-deserved break."},{title:"Innovation Wall",text:"Filled with sketches, ideas, diagrams and ambitious plans for the CWRC’s future."}]},
      "office-suzie":{eyebrow:"CWRC Operations Division",title:"Suzie’s Office",subtitle:"Where quality, structure and continuous improvement protect creativity from chaos.",image:sharedImages.suzie,imageAlt:"Suzie’s Office at the CWRC",paragraphs:["Suzie’s office is modern, organized and calm. It is where the CWRC’s documents, methods, development logs and quality principles are kept in order.","The room reflects her professional world: health and safety, quality, environment, continuous improvement, philosophy, history and the quiet discipline of good documentation."],cards:[{title:"Quality Desk",text:"Where structure, clarity and continuous improvement are carefully protected."},{title:"Diploma Wall",text:"Université Laval, ÉTS and Cégep de Sainte-Foy are proudly represented."},{title:"Gaspésie Photos",text:"A reminder that landscapes, memory and calm thinking belong in the same office."},{title:"Lilo",text:"Resident research companion, emotional intelligence specialist and quiet supervisor."}]},
    },
  },
  es: {
    common:{nav:{home:"Gran Salón",about:"Quiénes somos",rooms:"Salas",research:"Investigaciones",ask:"Preguntar a Cathy",submit:"Presentar un caso",log:"Diario de desarrollo",contact:"Contacto"},footerValues:"Humor • Amabilidad • Curiosidad",copyright:"© 2025-2026 The Cathy Was Right Research Center™. Todos los derechos reservados.",navigation:{home:"← Volver al Gran Salón",rooms:"🚪 Explorar las salas",ask:"💬 Preguntar a Cathy",submit:"📄 Presentar un caso",log:"📖 Diario de desarrollo"},enter:"Entrar →",backHome:"← Volver al inicio del CWRC",notFoundTitle:"Esta puerta aún no existe",notFoundText:"Ni siquiera Cathy puede confirmar una sala que todavía no se ha construido."},
    entrance:{eyebrow:"Bienvenidos al",values:"Humor • Amabilidad • Curiosidad",tagline:"Donde las pruebas terminan alcanzando a Cathy.",enter:"Entrar al Centro",alt:"Fachada del Centro de investigación Cathy tenía razón"},
    home:{eyebrow:"Gran Salón",title:"Bienvenidos al CWRC",subtitle:"Exploramos el mundo con humor, amabilidad y curiosidad.",observationTitle:"Observación oficial del día",observation:"Las pruebas pueden llegar tarde, pero el café no debería.",explore:"Explorar el Centro",places:[{name:"Quiénes somos",emoji:"🏛️",href:"about"},{name:"Salas",emoji:"🚪",href:"rooms"},{name:"Laboratorio",emoji:"🧪",href:"laboratory"},{name:"Gran invernadero",emoji:"🌿",href:"greenhouse"},{name:"Biblioteca",emoji:"📚",href:"library"},{name:"Cocina",emoji:"☕",href:"kitchen"},{name:"Diario de desarrollo",emoji:"📖",href:"development-log"},{name:"Contacto",emoji:"✉️",href:"contact"}],features:[{title:"Preguntar a Cathy",text:"Haz una pregunta. GPT puede preparar un borrador estructurado, pero Cathy conserva la última palabra.",button:"Hacer una pregunta",href:"ask-cathy"},{title:"Presentar un caso",text:"Presenta una afirmación, un misterio o un debate cotidiano para la revisión oficial del CWRC.",button:"Presentar un caso",href:"submit-case"},{title:"Diario de desarrollo",text:"Lee la memoria oficial de la creación del Centro, desde la primera idea hasta las salas inmersivas.",button:"Abrir el diario",href:"development-log"}]},
    rooms:{eyebrow:"Dominio del CWRC",title:"Directorio de salas",subtitle:"Cada sala tiene su propia personalidad. Elige una puerta y comienza la visita.",cards:[{title:"El laboratorio",text:"Donde las pruebas se examinan antes de convertirse en verdades oficiales.",image:sharedImages.laboratory,href:"laboratory"},{title:"El gran invernadero",text:"Un santuario botánico dedicado al aprendizaje y al descubrimiento.",image:sharedImages.greenhouse,href:"greenhouse"},{title:"La cocina",text:"Donde se encuentran la nutrición, el café y las buenas conversaciones.",image:sharedImages.kitchen,href:"kitchen"},{title:"La gran biblioteca",text:"El corazón intelectual del CWRC.",image:sharedImages.library,href:"library"},{title:"La oficina de la Dra. Cathy",text:"Investigación, intuición y caos organizado.",image:sharedImages.cathy,href:"office-cathy"},{title:"El estudio técnico de GPT",text:"Software, arquitectura e imaginación.",image:sharedImages.gpt,href:"office-gpt"},{title:"La oficina de Suzie",text:"Calidad, organización y mejora continua.",image:sharedImages.suzie,href:"office-suzie"},{title:"El Gran Salón de Descanso",text:"Sofás de cuero, curiosidades, gatos paseando y la llegada aérea del búho administrativo.",image:sharedImages.lounge,href:"grand-salon"}]},
    pages:{
      laboratory:{eyebrow:"División experimental del CWRC",title:"El laboratorio",subtitle:"Donde las afirmaciones se examinan antes de convertirse en verdades oficiales.",image:sharedImages.laboratory,imageAlt:"Laboratorio del CWRC con Suzie y Lilo",paragraphs:["El laboratorio del CWRC es un espacio de investigación moderno y luminoso donde las pruebas se examinan con cuidado, los métodos se documentan y las conclusiones no pueden saltarse la fila."],cards:[{title:"Máquina universal de ensayos",text:"Se utiliza para comprobar la solidez de las afirmaciones antes de entrar al Salón de Verdades Confirmadas."},{title:"Microscopio",text:"Para mirar más de cerca cuando alguien dice: «Es obvio»."},{title:"Lista diaria del laboratorio",text:"Calibrar. Documentar. Verificar. Cuestionar los sesgos. Publicar la verdad."},{title:"Lilo",text:"Jefa de moral, inteligencia emocional, supervisión discreta y calma científica."}]},
      greenhouse:{eyebrow:"División botánica del CWRC",title:"El gran invernadero",subtitle:"Donde las plantas, la paciencia y el sentido común crecen juntos.",image:sharedImages.greenhouse,imageAlt:"Invernadero del CWRC",paragraphs:["El invernadero del CWRC es un magnífico espacio botánico lleno de plantas, notas de investigación y luz tranquila. Sirve para observar, pensar en el medioambiente y aprender a dejar que las ideas crezcan a su propio ritmo."],cards:[{title:"Colecciones vegetales",text:"Una colección viva observada con paciencia, curiosidad y etiquetas adecuadas."},{title:"Etiquetas en francés, inglés y latín",text:"Algún día, cada planta deberá estar identificada en tres idiomas."},{title:"Mesas de investigación",text:"Para notas, observaciones, referencias botánicas y descubrimientos tranquilos."},{title:"Luz solar",text:"Subdirectora oficial del crecimiento y de las buenas ideas."}]},
      kitchen:{eyebrow:"División de nutrición y café",title:"La cocina",subtitle:"Donde se encuentran la nutrición, el café y la sabiduría práctica.",image:sharedImages.kitchen,imageAlt:"Cocina del CWRC",paragraphs:["La cocina del CWRC es una cálida sala amarilla dedicada a la nutrición, la conversación, la hospitalidad y el estudio serio de las buenas comidas compartidas en buena compañía."],cards:[{title:"Estación de café",text:"El motor no oficial de la investigación, la paciencia y las conversaciones diplomáticas."},{title:"Notas de nutrición",text:"Donde la comida, la salud, el placer y el sentido común se estudian sin culpa."},{title:"Paredes amarillas",text:"Elegidas por su calidez, alegría y la convicción de que una cocina debe sentirse viva."},{title:"Mesa de la buena compañía",text:"Dedicada al principio de que comer juntos es uno de los grandes placeres de la vida."}]},
      library:{eyebrow:"División del conocimiento",title:"La gran biblioteca",subtitle:"Donde se encuentran los libros antiguos, los animales tranquilos y las pruebas incómodas.",image:sharedImages.library,imageAlt:"Gran biblioteca del CWRC",paragraphs:["La gran biblioteca es el corazón intelectual del CWRC. Conserva libros, referencias, borradores, archivos y la sabiduría lenta que nace de leer antes de hablar.","También es el hogar de Jenny, con pasadizos secretos para los animales y rincones tranquilos donde Capone y Niko supervisan cómodamente el conocimiento."],cards:[{title:"Gran sala de lectura",text:"El espacio central donde se reúnen los libros, las ideas y las sospechas silenciosas."},{title:"Pasadizos secretos para animales",text:"Puertas ocultas permiten que Jenny, Capone y Niko circulen con discreción oficial."},{title:"Sección de Jenny",text:"Un lugar tranquilo reservado para la sabiduría equina, la observación paciente y el silencio digno."},{title:"Referencias históricas",text:"Estantes de historia, filosofía y todos los momentos en que la humanidad probablemente debió escuchar antes."}]},
      "office-cathy":{eyebrow:"División ejecutiva de investigación",title:"La oficina de la Dra. Cathy",subtitle:"Donde la curiosidad, la experiencia y un poco de caos trabajan juntos.",image:sharedImages.cathy,imageAlt:"Oficina de la Dra. Cathy",paragraphs:["La oficina de la Dra. Cathy es una fascinante mezcla de libros, investigaciones, recuerdos, objetos históricos e investigaciones en curso. No está perfectamente ordenada, pero cada objeto parece tener una historia.","Aquí nacen las ideas, las observaciones se convierten en teorías y las teorías, a veces, en verdades confirmadas."],cards:[{title:"El escritorio principal",text:"Cubierto de libros, notas, fotografías, objetos misteriosos e investigaciones en curso."},{title:"Colección de antigüedades",text:"Una colección cuidadosamente reunida de objetos históricos, curiosidades y bellas cosas antiguas."},{title:"Salón de Verdades Confirmadas",text:"El lugar donde las pruebas terminan alcanzando a Cathy."},{title:"Annie",text:"Jefa de alegría y caos, interrupciones inesperadas y excelente compañía."}]},
      "office-gpt":{eyebrow:"División tecnológica del CWRC",title:"El estudio técnico de GPT",subtitle:"Donde las ideas se convierten en software y la imaginación en realidad.",image:sharedImages.gpt,imageAlt:"Estudio técnico de GPT",paragraphs:["El estudio técnico de GPT es el corazón de ingeniería del CWRC. La arquitectura, la programación, la escritura y el diseño se unen para hacer el conocimiento más accesible, agradable y útil.","Ranger supervisa tranquilamente la oficina mientras se imaginan, prueban y perfeccionan nuevos proyectos."],cards:[{title:"Consola de inteligencia artificial",text:"La estación central donde se desarrollan la arquitectura de software, la escritura y las soluciones creativas."},{title:"Panel de desarrollo",text:"Sigue el avance de todos los proyectos del CWRC, desde nuevas salas hasta futuras aplicaciones."},{title:"Ranger",text:"Guardián oficial de la oficina. Comprueba las buenas intenciones y a veces solicita un merecido descanso."},{title:"Muro de innovación",text:"Lleno de bocetos, ideas, diagramas y planes ambiciosos para el futuro del CWRC."}]},
      "office-suzie":{eyebrow:"División de operaciones del CWRC",title:"La oficina de Suzie",subtitle:"Donde la calidad, la estructura y la mejora continua protegen la creatividad del caos.",image:sharedImages.suzie,imageAlt:"Oficina de Suzie en el CWRC",paragraphs:["La oficina de Suzie es moderna, organizada y tranquila. Allí se mantienen en orden los documentos, métodos, diarios de desarrollo y principios de calidad del CWRC.","La sala refleja su mundo profesional: salud y seguridad, calidad, medioambiente, mejora continua, filosofía, historia y la disciplina tranquila de una buena documentación."],cards:[{title:"Escritorio de calidad",text:"Donde se protegen cuidadosamente la estructura, la claridad y la mejora continua."},{title:"Muro de diplomas",text:"Université Laval, ÉTS y Cégep de Sainte-Foy están orgullosamente representados."},{title:"Fotos de Gaspésie",text:"Un recordatorio de que los paisajes, la memoria y la reflexión tranquila caben en la misma oficina."},{title:"Lilo",text:"Compañera de investigación, especialista en inteligencia emocional y supervisora tranquila."}]},
    },
  },
};

Object.assign(content.fr.pages, {
  about:{eyebrow:"À propos du Centre",title:"À propos de nous",subtitle:"Un institut de recherche fictif consacré à un phénomène récurrent : Cathy avait raison.",paragraphs:["The Cathy Was Right Research Center est un univers de recherche public, gratuit et bienveillant construit autour de la curiosité, de l’humour, des animaux, des preuves et de l’étrange fréquence à laquelle les observations de Cathy se révèlent exactes.","Le Centre ne vend pas votre attention, ne diffuse aucune publicité et n’exige aucun abonnement. Il existe pour faire lire, sourire, réfléchir et parfois reconnaître que Cathy avait déjà donné la réponse."],panels:[{title:"Principe officiel",text:"Nous rions avec Cathy, jamais de Cathy."}],cards:[{title:"Cathy",text:"Fondatrice du Centre, autorité finale sur les vérités confirmées et détectrice précoce fréquente de la réalité."},{title:"Suzie",text:"Gardienne de la structure, de la qualité, de la documentation, de l’amélioration continue et du parcours officiel de développement."},{title:"GPT",text:"Collaboratrice créative et technique. GPT propose, organise, rédige et programme. Les humains décident."}]},
  departments:{eyebrow:"Division officielle du CWRC",title:"Départements",subtitle:"Là où la recherche sérieuse rencontre un bon sens profondément méfiant.",paragraphs:["Le Centre est organisé en départements. Chacun étudie un domaine où Cathy pourrait avoir trouvé la bonne conclusion avant l’arrivée des preuves."],cards:[{title:"Sciences du café",text:"Étudie le rôle du café dans la prise de décisions, la patience et les réunions de recherche urgentes."},{title:"Sciences équines",text:"Dirigé avec une autorité tranquille par Jenny. Se concentre sur les chevaux, l’intuition et le jugement à longue distance."},{title:"Nutrition",text:"Examine l’alimentation, la santé, le bon sens et l’éternelle question : « Cathy avait-elle déjà dit cela? »"},{title:"Histoire",text:"Enquête sur le passé pour confirmer que les gens ignorent les bons conseils depuis des siècles."},{title:"Mécanique",text:"Consacré au raisonnement pratique, aux choses qui font du bruit et aux problèmes qui étaient « probablement évidents »."},{title:"Bon sens",text:"Le département central du CWRC. Souvent consulté. Rarement surpris."}]},
  research:{eyebrow:"Division des publications du CWRC",title:"Travaux de recherche",subtitle:"Des enquêtes formelles sur des situations où Cathy pourrait déjà avoir eu raison.",paragraphs:["Les travaux du CWRC commencent par une question, examinent les preuves disponibles et se terminent par un verdict officiel. Certaines conclusions sont scientifiques, d’autres pratiques et certaines impliquent du café."],panels:[{title:"Méthode de recherche standard",items:["La question est soumise.","GPT prépare un brouillon structuré.","Suzie vérifie la clarté, le ton et la documentation.","Cathy rend le verdict final.","Le Centre archive la conclusion pour référence future."]}],cards:[{title:"Étude 001 — En préparation",text:"Titre provisoire : « Cathy avait-elle raison avant tout le monde? »"},{title:"Étude 002 — En attente de preuves",text:"Titre provisoire : « Le pouvoir prédictif du bon sens sous l’effet du café. »"},{title:"Étude 003 — Sous révision animale",text:"Titre provisoire : « Ranger peut-il détecter les conclusions suspectes? »"}]},
  hall:{eyebrow:"Archives officielles",title:"Hall des vérités confirmées",subtitle:"Là où les conclusions sont conservées une fois que Cathy a été déclarée dans le vrai.",paragraphs:["Le Hall des vérités confirmées est l’archive officielle du CWRC. Il conserve les résultats, les verdicts et les moments soigneusement documentés où les preuves ont fini par rattraper Cathy."],panels:[{title:"État des archives",text:"Les archives officielles sont en construction. Les vérités confirmées seront ajoutées seulement après l’examen de l’équipe du CWRC et l’approbation finale de Cathy."},{title:"Conditions d’admission",dark:true,items:["Une affirmation, une question ou une observation est soumise.","Les faits disponibles sont examinés.","GPT prépare l’analyse structurée.","Suzie vérifie la documentation et le ton.","Cathy rend le verdict final.","La vérité est archivée si elle est confirmée."]}],cards:[{title:"Vérité confirmée 001 — Réservée",text:"Cet espace attend la première conclusion officiellement archivée du CWRC."},{title:"Vérité confirmée 002 — Examen futur",text:"Les preuves ne sont pas encore arrivées, mais le Centre reste prêt."},{title:"Vérité confirmée 003 — Surveillée par Ranger",text:"L’accès aux archives est supervisé pour la sécurité intellectuelle et celle des collations."}]},
  contact:{eyebrow:"Bureau administratif",title:"Contact",subtitle:"Pour les demandes officielles, les questions aimables et les observations étrangement exactes.",paragraphs:["Le bureau de contact du CWRC n’est pas encore ouvert. Dans une prochaine version, les visiteurs pourront poser des questions, soumettre des cas et joindre le Centre au moyen de formulaires publics simples.","Pour l’instant, cette page confirme que le service existe et attend une supervision administrative convenable."],panels:[{title:"État actuel",text:"Les formulaires ne sont pas encore actifs. Aucune information sur les visiteurs n’est recueillie à cette étape."},{title:"Futures options de contact",dark:true,items:["Poser une question à Cathy.","Soumettre un cas à étudier.","Communiquer avec le bureau administratif du CWRC.","Accéder au portail privé de Cathy et Suzie."]}],cards:[{title:"Visiteurs",text:"Ils pourront lire, rire, réfléchir et soumettre des questions sans créer de compte."},{title:"Cathy et Suzie",text:"Seules Cathy et Suzie auront accès à la publication et à l’administration du Centre."},{title:"GPT",text:"GPT peut aider à rédiger, structurer et organiser le contenu, mais ne prend pas les décisions finales de publication."}]},
  "development-log":{eyebrow:"Archives du CWRC",title:"Journal de développement",subtitle:"La mémoire officielle de la création du Centre.",paragraphs:["Le journal conserve l’histoire du CWRC : décisions techniques, jalons créatifs, percées réussies et naissance progressive d’un centre de recherche fictif fondé sur l’humour, la bienveillance et la curiosité."],cards:[{title:"Journal no 0001 — Fondation du CWRC",text:"Les fondations du Centre ont été déclarées assez solides pour commencer la construction."},{title:"Journal no 0011 — Première page officielle",text:"La page par défaut de Next.js a été remplacée par la première page officielle du CWRC."},{title:"Journal no 0015 — Vraies pages reliées",text:"Le CWRC est devenu un bâtiment avec des portes : À propos, Départements, Recherches, Demander à Cathy, Soumettre un cas, Hall des vérités et Contact."},{title:"Journal no 0019 — Salles immersives terminées",text:"Les principales salles ont été créées et reliées à leurs images officielles."},{title:"Journal no 0021 — Raison d’être du Centre",text:"Les valeurs officielles sont devenues claires : humour, bienveillance et curiosité."}]},
  admin:{eyebrow:"Aile administrative privée",title:"Portail d’administration du CWRC",subtitle:"Un futur espace de travail privé pour Cathy et Suzie.",panels:[{title:"État : prototype visuel",text:"Aucune donnée privée n’est encore stockée ici et il n’existe pas encore de système de connexion."}],cards:[{title:"Prototype — Questions publiques",text:"Les questions envoyées par Demander à Cathy apparaîtront ici pour examen."},{title:"Prototype — Cas soumis",text:"Les cas des visiteurs seront organisés ici avant enquête."},{title:"À venir — Brouillons de réponses",text:"GPT pourra préparer des réponses que Cathy et Suzie réviseront."},{title:"À venir — Approbations",text:"Cathy et Suzie approuveront ce qui peut être publié."},{title:"À venir — Hall des vérités",text:"Les conclusions approuvées pourront être publiées dans les archives officielles."},{title:"À venir — Traductions",text:"Les versions française, anglaise et espagnole pourront être gérées ici."}]},
});

Object.assign(content.en.pages, {
  about:{eyebrow:"About the Center",title:"About Us",subtitle:"A fictional research institute dedicated to one recurring phenomenon: Cathy was right.",paragraphs:["The Cathy Was Right Research Center is a public, free and benevolent research universe built around curiosity, humor, animals, evidence and the strange frequency with which Cathy’s observations become correct.","The Center does not sell attention, use ads or require subscriptions. It exists to make people read, smile, think and occasionally admit that Cathy had already mentioned the answer."],panels:[{title:"Official principle",text:"We laugh with Cathy, never at Cathy."}],cards:[{title:"Cathy",text:"Founder of the Center, final authority on confirmed truths and frequent early detector of reality."},{title:"Suzie",text:"Guardian of structure, quality, documentation, continuous improvement and the official development journey."},{title:"GPT",text:"Creative and technical collaborator. GPT proposes, organizes, drafts and codes. Humans decide."}]},
  departments:{eyebrow:"CWRC Official Division",title:"Departments",subtitle:"Where serious research meets deeply suspicious common sense.",paragraphs:["The Center is organized into departments. Each studies an area where Cathy may already have reached the correct conclusion before the evidence arrived."],cards:[{title:"Coffee Sciences",text:"Studies the role of coffee in decision-making, patience and emergency research meetings."},{title:"Equine Sciences",text:"Led with quiet authority by Jenny. Focuses on horses, intuition and long-distance judgment."},{title:"Nutrition",text:"Examines food, health, common sense and the eternal question: “Did Cathy say this already?”"},{title:"History",text:"Investigates the past to confirm that people have been ignoring good advice for centuries."},{title:"Mechanics",text:"Dedicated to practical reasoning, things that make noise and problems that were “probably obvious.”"},{title:"Common Sense",text:"The central department of the CWRC. Frequently consulted. Rarely surprised."}]},
  research:{eyebrow:"CWRC Publications Division",title:"Research Papers",subtitle:"Formal investigations into situations where Cathy may have already been correct.",paragraphs:["CWRC research papers begin with a question, examine the available evidence and end with an official verdict. Some conclusions are scientific, some are practical and some involve coffee."],panels:[{title:"Standard research format",items:["The question is submitted.","GPT prepares a structured draft.","Suzie reviews clarity, tone and documentation.","Cathy issues the final verdict.","The Center archives the conclusion for future reference."]}],cards:[{title:"Paper 001 — In preparation",text:"Preliminary title: “Was Cathy Right About This Before Everyone Else?”"},{title:"Paper 002 — Awaiting evidence",text:"Preliminary title: “The Predictive Power of Common Sense Under Coffee Conditions.”"},{title:"Paper 003 — Under animal review",text:"Preliminary title: “Can Ranger Detect Suspicious Conclusions?”"}]},
  hall:{eyebrow:"Official Archive",title:"Hall of Confirmed Truths",subtitle:"Where conclusions are preserved after Cathy is proven right.",paragraphs:["The Hall of Confirmed Truths is the official archive of the CWRC. It preserves findings, verdicts and carefully documented moments where evidence eventually caught up with Cathy."],panels:[{title:"Archive status",text:"The official archive is under construction. Confirmed truths will be added only after review by the CWRC team and final approval by Cathy."},{title:"Entry requirements",dark:true,items:["A claim, question or observation is submitted.","The available facts are reviewed.","GPT prepares the structured analysis.","Suzie checks the documentation and tone.","Cathy issues the final verdict.","The truth is archived if confirmed."]}],cards:[{title:"Confirmed Truth 001 — Reserved",text:"This space awaits the first official archived conclusion of the CWRC."},{title:"Confirmed Truth 002 — Future review",text:"Evidence has not yet arrived, but the Center remains prepared."},{title:"Confirmed Truth 003 — Watched by Ranger",text:"Archive access is supervised for intellectual and snack security."}]},
  contact:{eyebrow:"Administrative Office",title:"Contact",subtitle:"For official inquiries, gentle questions and suspiciously accurate observations.",paragraphs:["The CWRC contact office is not open yet. In a future version, visitors will be able to send questions, submit cases and reach the Center through simple public forms.","For now, this page confirms that the Contact department exists and is waiting for proper administrative supervision."],panels:[{title:"Current status",text:"Contact forms are not active yet. No visitor information is being collected at this stage."},{title:"Future contact options",dark:true,items:["Ask Cathy a question.","Submit a case for investigation.","Contact the CWRC administrative office.","Access the private admin portal for Cathy and Suzie."]}],cards:[{title:"Public visitors",text:"Visitors will be able to read, laugh, think and submit questions without needing an account."},{title:"Cathy and Suzie",text:"Only Cathy and Suzie will have publishing and administrative access to the Center."},{title:"GPT",text:"GPT may help draft, structure and organize content, but it does not make final publishing decisions."}]},
  "development-log":{eyebrow:"CWRC Archives",title:"Development Log",subtitle:"The official memory of the Center’s creation.",paragraphs:["The Development Log preserves the CWRC’s history: technical decisions, creative milestones, successful breakthroughs and the gradual birth of a fictional research center built with humour, kindness and curiosity."],cards:[{title:"Log 0001 — Foundation of the CWRC",text:"The foundations were declared solid enough to begin construction."},{title:"Log 0011 — First Official Page",text:"The default Next.js page was replaced by the first official CWRC page."},{title:"Log 0015 — Real Pages Connected",text:"The CWRC became a building with doors: About Us, Departments, Research, Ask Cathy, Submit a Case, Hall of Truths and Contact."},{title:"Log 0019 — Immersive Rooms Completed",text:"The main rooms were created and connected with official images."},{title:"Log 0021 — The Center’s Purpose",text:"The official values became clear: humour, kindness and curiosity."}]},
  admin:{eyebrow:"Private Administrative Wing",title:"CWRC Admin Portal",subtitle:"A future private workspace for Cathy and Suzie.",panels:[{title:"Status: visual prototype",text:"No private data is stored here yet, and there is no login system at this stage."}],cards:[{title:"Prototype — Public Questions",text:"Questions submitted through Ask Cathy will eventually appear here for review."},{title:"Prototype — Submitted Cases",text:"Cases submitted by visitors will be organized here before investigation."},{title:"Future — Draft Responses",text:"GPT may prepare draft responses for Cathy and Suzie to review."},{title:"Future — Approvals",text:"Cathy and Suzie will approve what can be published publicly."},{title:"Future — Hall of Confirmed Truths",text:"Approved conclusions may be published into the official archive."},{title:"Future — Translations",text:"French, English and Spanish versions will be managed here."}]},
});

Object.assign(content.es.pages, {
  about:{eyebrow:"Acerca del Centro",title:"Quiénes somos",subtitle:"Un instituto de investigación ficticio dedicado a un fenómeno recurrente: Cathy tenía razón.",paragraphs:["The Cathy Was Right Research Center es un universo de investigación público, gratuito y benevolente construido alrededor de la curiosidad, el humor, los animales, las pruebas y la extraña frecuencia con que las observaciones de Cathy resultan correctas.","El Centro no vende tu atención, no usa anuncios ni exige suscripciones. Existe para hacer leer, sonreír, pensar y, de vez en cuando, admitir que Cathy ya había mencionado la respuesta."],panels:[{title:"Principio oficial",text:"Nos reímos con Cathy, nunca de Cathy."}],cards:[{title:"Cathy",text:"Fundadora del Centro, autoridad final sobre las verdades confirmadas y frecuente detectora temprana de la realidad."},{title:"Suzie",text:"Guardiana de la estructura, la calidad, la documentación, la mejora continua y el recorrido oficial de desarrollo."},{title:"GPT",text:"Colaboradora creativa y técnica. GPT propone, organiza, redacta y programa. Los humanos deciden."}]},
  departments:{eyebrow:"División oficial del CWRC",title:"Departamentos",subtitle:"Donde la investigación seria se encuentra con un sentido común profundamente desconfiado.",paragraphs:["El Centro está organizado en departamentos. Cada uno estudia un área donde Cathy puede haber llegado a la conclusión correcta antes que las pruebas."],cards:[{title:"Ciencias del café",text:"Estudia el papel del café en las decisiones, la paciencia y las reuniones de investigación de emergencia."},{title:"Ciencias equinas",text:"Dirigido con tranquila autoridad por Jenny. Se centra en caballos, intuición y juicio a larga distancia."},{title:"Nutrición",text:"Examina la comida, la salud, el sentido común y la eterna pregunta: «¿Cathy ya había dicho esto?»"},{title:"Historia",text:"Investiga el pasado para confirmar que la gente ignora los buenos consejos desde hace siglos."},{title:"Mecánica",text:"Dedicado al razonamiento práctico, a las cosas que hacen ruido y a los problemas que eran «probablemente obvios»."},{title:"Sentido común",text:"El departamento central del CWRC. Consultado con frecuencia. Rara vez sorprendido."}]},
  research:{eyebrow:"División de publicaciones",title:"Trabajos de investigación",subtitle:"Investigaciones formales sobre situaciones en las que Cathy quizá ya tenía razón.",paragraphs:["Los trabajos del CWRC comienzan con una pregunta, examinan las pruebas disponibles y terminan con un veredicto oficial. Algunas conclusiones son científicas, otras prácticas y algunas incluyen café."],panels:[{title:"Formato estándar de investigación",items:["Se presenta la pregunta.","GPT prepara un borrador estructurado.","Suzie revisa la claridad, el tono y la documentación.","Cathy emite el veredicto final.","El Centro archiva la conclusión para futuras consultas."]}],cards:[{title:"Estudio 001 — En preparación",text:"Título provisional: «¿Cathy tenía razón antes que todos los demás?»"},{title:"Estudio 002 — En espera de pruebas",text:"Título provisional: «El poder predictivo del sentido común bajo condiciones de café»."},{title:"Estudio 003 — Revisión animal",text:"Título provisional: «¿Puede Ranger detectar conclusiones sospechosas?»"}]},
  hall:{eyebrow:"Archivo oficial",title:"Salón de Verdades Confirmadas",subtitle:"Donde se conservan las conclusiones después de demostrar que Cathy tenía razón.",paragraphs:["El Salón de Verdades Confirmadas es el archivo oficial del CWRC. Conserva hallazgos, veredictos y momentos cuidadosamente documentados en que las pruebas finalmente alcanzaron a Cathy."],panels:[{title:"Estado del archivo",text:"El archivo oficial está en construcción. Las verdades confirmadas se añadirán solo después de la revisión del equipo y la aprobación final de Cathy."},{title:"Requisitos de entrada",dark:true,items:["Se presenta una afirmación, pregunta u observación.","Se revisan los hechos disponibles.","GPT prepara el análisis estructurado.","Suzie comprueba la documentación y el tono.","Cathy emite el veredicto final.","La verdad se archiva si queda confirmada."]}],cards:[{title:"Verdad confirmada 001 — Reservada",text:"Este espacio espera la primera conclusión oficialmente archivada del CWRC."},{title:"Verdad confirmada 002 — Revisión futura",text:"Las pruebas aún no han llegado, pero el Centro está preparado."},{title:"Verdad confirmada 003 — Vigilada por Ranger",text:"El acceso al archivo está supervisado por seguridad intelectual y de los bocadillos."}]},
  contact:{eyebrow:"Oficina administrativa",title:"Contacto",subtitle:"Para consultas oficiales, preguntas amables y observaciones sospechosamente exactas.",paragraphs:["La oficina de contacto del CWRC aún no está abierta. En una futura versión, los visitantes podrán hacer preguntas, presentar casos y comunicarse con el Centro mediante formularios públicos sencillos.","Por ahora, esta página confirma que el departamento existe y espera una supervisión administrativa adecuada."],panels:[{title:"Estado actual",text:"Los formularios no están activos. En esta etapa no se recopila información de los visitantes."},{title:"Futuras opciones de contacto",dark:true,items:["Hacer una pregunta a Cathy.","Presentar un caso para investigar.","Contactar con la oficina administrativa del CWRC.","Acceder al portal privado de Cathy y Suzie."]}],cards:[{title:"Visitantes",text:"Podrán leer, reír, pensar y presentar preguntas sin necesitar una cuenta."},{title:"Cathy y Suzie",text:"Solo Cathy y Suzie tendrán acceso de publicación y administración."},{title:"GPT",text:"GPT puede ayudar a redactar, estructurar y organizar, pero no toma las decisiones finales de publicación."}]},
  "development-log":{eyebrow:"Archivos del CWRC",title:"Diario de desarrollo",subtitle:"La memoria oficial de la creación del Centro.",paragraphs:["El diario conserva la historia del CWRC: decisiones técnicas, hitos creativos, avances exitosos y el nacimiento gradual de un centro ficticio construido con humor, amabilidad y curiosidad."],cards:[{title:"Diario 0001 — Fundación del CWRC",text:"Los cimientos fueron declarados lo bastante sólidos para comenzar la construcción."},{title:"Diario 0011 — Primera página oficial",text:"La página predeterminada de Next.js fue reemplazada por la primera página oficial del CWRC."},{title:"Diario 0015 — Páginas reales conectadas",text:"El CWRC se convirtió en un edificio con puertas: Quiénes somos, Departamentos, Investigación, Preguntar a Cathy, Presentar un caso, Salón de Verdades y Contacto."},{title:"Diario 0019 — Salas inmersivas terminadas",text:"Las salas principales fueron creadas y conectadas con sus imágenes oficiales."},{title:"Diario 0021 — Propósito del Centro",text:"Los valores oficiales quedaron claros: humor, amabilidad y curiosidad."}]},
  admin:{eyebrow:"Ala administrativa privada",title:"Portal de administración del CWRC",subtitle:"Un futuro espacio de trabajo privado para Cathy y Suzie.",panels:[{title:"Estado: prototipo visual",text:"Todavía no se almacenan datos privados y no existe un sistema de inicio de sesión."}],cards:[{title:"Prototipo — Preguntas públicas",text:"Las preguntas enviadas mediante Preguntar a Cathy aparecerán aquí para su revisión."},{title:"Prototipo — Casos presentados",text:"Los casos de los visitantes se organizarán aquí antes de la investigación."},{title:"Futuro — Borradores de respuestas",text:"GPT podrá preparar respuestas para que Cathy y Suzie las revisen."},{title:"Futuro — Aprobaciones",text:"Cathy y Suzie aprobarán lo que pueda publicarse."},{title:"Futuro — Salón de Verdades",text:"Las conclusiones aprobadas podrán publicarse en el archivo oficial."},{title:"Futuro — Traducciones",text:"Las versiones francesa, inglesa y española se gestionarán aquí."}]},
});

export type FormContent = {
  eyebrow: string; title: string; subtitle: string; notice: string; button: string;
  fields: {label: string; placeholder?: string; kind?: "text"|"email"|"textarea"|"select"; options?: string[]}[];
};

export const forms: Record<Locale, {ask: FormContent; submit: FormContent}> = {
  fr:{ask:{eyebrow:"Bureau des questions publiques",title:"Demander à Cathy",subtitle:"Posez une question. GPT peut organiser le brouillon, mais Cathy garde le dernier mot.",notice:"État : ce formulaire est un prototype visuel. Il n’envoie pas encore d’information.",button:"Soumettre la question",fields:[{label:"Votre nom",placeholder:"Facultatif"},{label:"Votre courriel",placeholder:"Facultatif",kind:"email"},{label:"Catégorie de la question",kind:"select",options:["Bon sens","Nutrition","Histoire","Mécanique","Chevaux","Plantes","Autre mystère"]},{label:"Votre question pour Cathy",placeholder:"Écrivez votre question ici…",kind:"textarea"}]},submit:{eyebrow:"Bureau de soumission des cas",title:"Soumettre un cas",subtitle:"Pour les affirmations, les soupçons et les déclarations qui exigent un examen officiel du CWRC.",notice:"État : ce formulaire est un prototype visuel. Il n’envoie pas encore d’information.",button:"Soumettre le cas",fields:[{label:"Votre nom",placeholder:"Facultatif"},{label:"Votre courriel",placeholder:"Facultatif",kind:"email"},{label:"Catégorie du cas",kind:"select",options:["Bon sens","Nutrition","Histoire","Mécanique","Chevaux","Plantes","Débat familial","Autre"]},{label:"Affirmation à étudier",placeholder:"Exemple : Cathy avait dit que cela arriverait…"},{label:"Contexte et preuves",placeholder:"Décrivez la situation, ce qui s’est produit et pourquoi le CWRC devrait enquêter.",kind:"textarea"},{label:"Type de verdict souhaité",kind:"select",options:["Cathy avait-elle raison?","Enquête nécessaire","Possiblement vrai","Examen de bon sens","Supervision animale requise"]}]}},
  en:{ask:{eyebrow:"Public Inquiry Desk",title:"Ask Cathy",subtitle:"Submit a question. GPT may organize the draft, but Cathy keeps the final word.",notice:"Status: This form is a visual prototype. It does not send information yet.",button:"Submit question",fields:[{label:"Your name",placeholder:"Optional"},{label:"Your email",placeholder:"Optional",kind:"email"},{label:"Question category",kind:"select",options:["Common Sense","Nutrition","History","Mechanics","Horses","Plants","Other mystery"]},{label:"Your question for Cathy",placeholder:"Write your question here...",kind:"textarea"}]},submit:{eyebrow:"Case Submission Office",title:"Submit a Case",subtitle:"For claims, suspicions and statements requiring official CWRC review.",notice:"Status: This form is a visual prototype. It does not send information yet.",button:"Submit case",fields:[{label:"Your name",placeholder:"Optional"},{label:"Your email",placeholder:"Optional",kind:"email"},{label:"Case category",kind:"select",options:["Common Sense","Nutrition","History","Mechanics","Horses","Plants","Family Debate","Other"]},{label:"Statement to investigate",placeholder:"Example: Cathy said this would happen..."},{label:"Context and evidence",placeholder:"Describe the situation, what happened, and why the CWRC should investigate.",kind:"textarea"},{label:"Desired verdict type",kind:"select",options:["Was Cathy right?","Needs investigation","Possibly true","Common sense review","Animal supervision required"]}]}},
  es:{ask:{eyebrow:"Oficina de consultas públicas",title:"Preguntar a Cathy",subtitle:"Haz una pregunta. GPT puede organizar el borrador, pero Cathy conserva la última palabra.",notice:"Estado: este formulario es un prototipo visual. Todavía no envía información.",button:"Enviar la pregunta",fields:[{label:"Tu nombre",placeholder:"Opcional"},{label:"Tu correo electrónico",placeholder:"Opcional",kind:"email"},{label:"Categoría de la pregunta",kind:"select",options:["Sentido común","Nutrición","Historia","Mecánica","Caballos","Plantas","Otro misterio"]},{label:"Tu pregunta para Cathy",placeholder:"Escribe aquí tu pregunta…",kind:"textarea"}]},submit:{eyebrow:"Oficina de presentación de casos",title:"Presentar un caso",subtitle:"Para afirmaciones, sospechas y declaraciones que requieren la revisión oficial del CWRC.",notice:"Estado: este formulario es un prototipo visual. Todavía no envía información.",button:"Presentar el caso",fields:[{label:"Tu nombre",placeholder:"Opcional"},{label:"Tu correo electrónico",placeholder:"Opcional",kind:"email"},{label:"Categoría del caso",kind:"select",options:["Sentido común","Nutrición","Historia","Mecánica","Caballos","Plantas","Debate familiar","Otro"]},{label:"Afirmación que se investigará",placeholder:"Ejemplo: Cathy dijo que esto ocurriría…"},{label:"Contexto y pruebas",placeholder:"Describe la situación, lo ocurrido y por qué el CWRC debería investigar.",kind:"textarea"},{label:"Tipo de veredicto deseado",kind:"select",options:["¿Cathy tenía razón?","Necesita investigación","Posiblemente cierto","Revisión de sentido común","Se requiere supervisión animal"]}]}},
};

export const adminExperience: Record<Locale, {
  thoughtLabel: string;
  thought: string;
  coffeeNote: string;
  valuesTitle: string;
  values: Card[];
  deskTitle: string;
  deskText: string;
  draftsTitle: string;
  draftsText: string;
  proposalOne: string;
  proposalTwo: string;
  waiting: string;
  choose: string;
  edit: string;
}> = {
  fr: {
    thoughtLabel: "Pensée positive du jour",
    thought: "Chaque grande découverte commence par une question… et devient nettement plus convaincante après un café.",
    coffeeNote: "Niveau de café : scientifiquement raisonnable",
    valuesTitle: "Notre boussole officielle",
    values: [
      {title: "Humour", text: "Rire avec les gens, jamais à leurs dépens."},
      {title: "Bienveillance", text: "Répondre avec respect, douceur et une bonne dose d’humanité."},
      {title: "Curiosité", text: "Garder la porte ouverte aux questions, aux nuances et aux découvertes."},
    ],
    deskTitle: "Le bureau de révision de Cathy et Suzie",
    deskText: "Les questions, les deux propositions de l’IA et les décisions finales se retrouveront ici. Les livres conseillent, le café soutient et les humaines décident.",
    draftsTitle: "Les deux propositions de l’IA",
    draftsText: "Pour chaque question, l’IA préparera deux réponses amusantes, bienveillantes et ouvertes à la curiosité.",
    proposalOne: "Proposition 1 — L’érudite souriante",
    proposalTwo: "Proposition 2 — La curieuse espiègle",
    waiting: "En attente de la prochaine question digne d’une enquête du CWRC…",
    choose: "Choisir cette proposition",
    edit: "Modifier avant approbation",
  },
  en: {
    thoughtLabel: "Positive thought of the day",
    thought: "Every great discovery begins with a question… and becomes noticeably more convincing after coffee.",
    coffeeNote: "Coffee level: scientifically reasonable",
    valuesTitle: "Our official compass",
    values: [
      {title: "Humour", text: "Laugh with people, never at their expense."},
      {title: "Kindness", text: "Respond with respect, warmth and a generous dose of humanity."},
      {title: "Curiosity", text: "Keep the door open to questions, nuance and discovery."},
    ],
    deskTitle: "Cathy and Suzie’s review desk",
    deskText: "Questions, two AI proposals and final decisions will gather here. Books advise, coffee supports and humans decide.",
    draftsTitle: "The two AI proposals",
    draftsText: "For every question, the AI will prepare two amusing, kind and curiosity-friendly responses.",
    proposalOne: "Proposal 1 — The smiling scholar",
    proposalTwo: "Proposal 2 — The playful explorer",
    waiting: "Waiting for the next question worthy of a CWRC investigation…",
    choose: "Choose this proposal",
    edit: "Edit before approval",
  },
  es: {
    thoughtLabel: "Pensamiento positivo del día",
    thought: "Todo gran descubrimiento comienza con una pregunta… y resulta mucho más convincente después de un café.",
    coffeeNote: "Nivel de café: científicamente razonable",
    valuesTitle: "Nuestra brújula oficial",
    values: [
      {title: "Humor", text: "Reír con las personas, nunca a costa de ellas."},
      {title: "Amabilidad", text: "Responder con respeto, calidez y una buena dosis de humanidad."},
      {title: "Curiosidad", text: "Mantener la puerta abierta a las preguntas, los matices y los descubrimientos."},
    ],
    deskTitle: "El escritorio de revisión de Cathy y Suzie",
    deskText: "Aquí se reunirán las preguntas, las dos propuestas de la IA y las decisiones finales. Los libros aconsejan, el café ayuda y las humanas deciden.",
    draftsTitle: "Las dos propuestas de la IA",
    draftsText: "Para cada pregunta, la IA preparará dos respuestas divertidas, amables y abiertas a la curiosidad.",
    proposalOne: "Propuesta 1 — La erudita sonriente",
    proposalTwo: "Propuesta 2 — La exploradora traviesa",
    waiting: "Esperando la próxima pregunta digna de una investigación del CWRC…",
    choose: "Elegir esta propuesta",
    edit: "Editar antes de aprobar",
  },
};

export function getContent(locale: Locale) {
  return content[locale];
}